#version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_demo_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./demo
    container_name: backend_demo_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-db        #nome del servizio
      - DB_PORT=5432               #Porta interna del container Postgres
      - DB_NAME=${DB_NAME}         #Prende dal .env
      - DB_USER=${DB_USER}         #Prende dal .env
      - DB_PASSWORD=${DB_PASSWORD} #Prende dal .env
    depends_on:
      - postgres-db

  frontend:
    build:
      context: ./frontend #nome progetto react
      dockerfile: Dockerfile
    container_name: frontend_demo_container
    ports:
      - "3000:80" # Raggiungibile dal browser su http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: