version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_demo_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: demodb
    ports:
      - "8432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./demo
    container_name: backend_demo_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  postgres_data: