spring.application.name=demo

# SQLite Database (file locale)
spring.datasource.url=jdbc:sqlite:C:/progWeb/demo/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
