spring.application.name=demo

# Configurazione Database PostgreSQL



#ATTENZIONE!!! per lavorare con docker
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:8432}/${DB_NAME}
#ATTENZIONE!!! per lavorare con intellij
#spring.datasource.url=jdbc:postgresql://localhost:8432/demodb



spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL nei log (comodo in fase di sviluppo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
